# Generated by Django 5.1.5 on 2025-03-04 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voice_assistant', '0001_initial'),
    ]

    operations = [
    ]
