# Generated by Django 5.1.5 on 2025-03-05 06:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_assistant', '0002_auto_20250305_0301'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['timestamp']},
        ),
        migrations.RenameField(
            model_name='conversation',
            old_name='ai_response',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='user_input',
        ),
        migrations.AddField(
            model_name='conversation',
            name='speaker',
            field=models.CharField(default='assistant', max_length=20),
        ),
        migrations.AddField(
            model_name='conversation',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='voice_assistant.callsession'),
        ),
    ]
