# Generated by Django 4.2.7 on 2025-05-29 06:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('voice_assistant', '0003_callsession_alter_conversation_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 - Very Poor'), (2, '2 - Poor'), (3, '3 - Average'), (4, '4 - Good'), (5, '5 - Excellent')])),
                ('comments', models.TextField(blank=True, null=True)),
                ('helpful_aspects', models.TextField(blank=True, help_text='What was most helpful about this call?', null=True)),
                ('improvement_suggestions', models.TextField(blank=True, help_text='What could be improved?', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='voice_assistant.callsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
